### PR TITLE
Update Families.rst

### PR DESCRIPTION
**Pull request by frverdeja**
updated user guide link to 1.7 pdf

### CODE REVIEW

**Comment by frverdeja** [comment]
I edited 5 total pages.  Let me know if I need to do anything else @jmleroux

**Comment by jmleroux** [comment]
I see only one update. :(
Did you commit your changes after editing each file?

**Comment by frverdeja** [comment]
@jmleroux I couldn't figure out how to do it on one PR, accidentally created 5 PRs. 
 https://github.com/akeneo/ExcelInitBundle/pulls

**Comment by jmleroux** [comment]
OK, i see you made one PR per file.

**Review by jmleroux — CHANGES_REQUESTED** [review]
Two other dead links to fix

**Comment by frverdeja** [comment]
it looks like ExcelInitBundle/wiki is dead?   i have no idea what to do with that, i was just trying to help update the user guide links.

**Comment by jmleroux** [comment]
> it looks like ExcelInitBundle/wiki is dead? i have no idea what to do with that, i was just trying to help update the user guide links.

No problemo, i'll fix the other links. thx @frverdeja

**Pull request closed without merging**
